# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='min_donate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='target',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
