# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20170529_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donates', to='group.Target')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Зарегестрирован'), (1, 'Одобрен'), (2, 'Отклонён')], default=0)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('donate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='group.Donate')),
            ],
        ),
    ]
