# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_donate_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cur_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='int_id',
            field=models.IntegerField(null=True),
        ),
    ]
