# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20170529_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='int_id',
        ),
    ]
