# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_remove_order_int_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='commission',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Зарегестрирован'), (1, 'Одобрен'), (2, 'Отклонён'), (3, 'Отправлен')], default=0),
        ),
    ]
