# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20170530_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(choices=[(45, 'Яндекс Деньги'), (94, 'VISA'), (63, 'QIWI')], null=True)),
                ('purse', models.CharField(blank=True, max_length=64)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
            ],
        ),
    ]
