# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=16)),
                ('status', models.IntegerField(choices=[(0, 'Создан'), (1, 'В процессе'), (2, 'Выполнен'), (3, 'Отменён'), (4, 'Ошибка')], default=0)),
                ('amount', models.IntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sends', to='group.Wallet')),
            ],
        ),
    ]
