"""
Django settings for vk_app project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j7c4!qcwcsm9)w6xkzi7v$5_-e8haovzf9o*0e876%7y060h8c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['vdonate.pro']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'web',
    'group'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
#    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vk_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vk_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/html/vk/static'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 60 * 10
SESSION_SAVE_EVERY_REQUEST = True

API_URL = 'https://api.vk.com/method/{api_method}?{params}&access_token={token}&v={version}'
API_VERSION = '5.64'
API_ACCESS_TOKEN = 'a44e550fb78bd301c9522989e5865b78b4a4c9eccd56408d7203aa69d422ecabc9f4ea7d8f241f4808f24'
GROUP_ID = '1431470'
FONT = 'Roboto-Regular.ttf'

AVATARS_DIR = 'avatars'
COVERS_DIR = 'covers'
DEFAULT_AVATAR = os.path.join(MEDIA_ROOT, 'images', 'default_avatar.png')

API_CLOUD_CONVERT = 'vCnxlfssWw6UQZyB5S4etqKowOKCQt1K0V-Zxw6hypZgFSE5Pw4hRckiA2k8G_--PmxgULZhpUjQDCEZuZ0QoQ'
ABSOLUTE_URL = 'https://vdonate.pro'

BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Moscow'
CELERY_IMPORTS = (
    'core.utils.tasks',
)
CELERY_IGNORE_RESULT = True
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600*6}

LOG_PATH = os.path.join(BASE_DIR, 'logs')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'main_formatter': {
            'format': '%(asctime)s [%(name)s.%(levelname)s] '
                      '%(message)s '
                      '(%(filename)s:%(lineno)d)',
            'datefmt': "%Y.%m.%d %H:%M:%S",
        },
    },
    'handlers': {
        'main_handler': {
            'level': 'INFO',
            'filename': os.path.join(LOG_PATH, 'app.log'),
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'formatter': 'main_formatter',
            'when': 'midnight',
            'backupCount': 30
        }
    },
    'loggers': {
        'app': {
            'level': 'INFO',
            'handlers': ['main_handler', ],
        },
        'vk': {
            'level': 'INFO',
            'handlers': ['main_handler', ],
        },
        'payment': {
            'level': 'INFO',
            'handlers': ['main_handler', ],
        }
    }
}

MERCHAND_ID = '51227'
SECRET1 = 'gowxko6r'
SECRET2 = 'lbsrwwmi'
PAYMENT_URL = 'http://www.free-kassa.ru/merchant/cash.php'

WALLET_API_URL = 'https://wallet.free-kassa.ru/api_v1.php'
WALLET_ID = 'F102205356'
API_KEY = '939F34218B1222B4ADF0DE04FFB3D8FA'

ADMINS = [('Nikita', 'support@vdonate.pro'),]
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_HOST_USER = 'support@vdonate.pro'
EMAIL_HOST_PASSWORD = 's4eRgsjsl'
EMAIL_PORT = 587
EMAIL_USE_TLS = True